### ISSUE TITLE
Public run program

### ISSUE THREAD

**Issue by fabiomontefuscolo** [fintech-systems/virtualmin-api#20]
https://github.com/fintech-systems/virtualmin-api/blob/eb88dd9a9fd12b5ce02fbe0fa6b38d2d3b1a95e3/src/VirtualminApi.php#L171

Can runProgram be public?

We need that to call different plugins on virtualmin and would no make sense creating new pull-requests with methods for dealing with custom plugins, If runProgram is public, I can extend the class to create custom calls. Makes sense?

**Comment by eugenevdm** [comment]
Sounds good! I don't see any reason to keep it private.
